sudo: required
services:
- docker
env:
  global:
  - AWS_S3_BUCKET=docs-v2.kuzzle.io
  - secure: e2j8CdD86voR0FKnDzo0BYIysfDjAdUW6FfO42VSaLPV97DjKdJd5dlhtDq+0U2/ae1iL3YpLlbVKr+wveS21hl15+jG+8miShnScGn3bhwe6P11uLCs9JL/WfoJ0vHueLy3XWHE8R51Mu2lD5aFJxQBRExQ06zS4rjev/ZFiipRlLFsYFeKgZ7I0WKo6Aqqt9wP7SFfuvr5jNLwgDIMvi9rWP+ZlbZIzm7of7QAzJfBK17VwszCatBlREWzXTGgxnVK09fJJdCZ9gTWwrayXxif+DVFCkCuKgG12glh1R3k5EBu7IkJsqCdTWYJ5AC2OBaMOvwpE3d340j0xvnDtmVUArDPJohQiBN6GTOo8R54AKbOE25U1YKSPqZ7pJplsvRjkpdlCnGVXmR+W/2HdWK6uSXyg/iYncb4DVVPnqk/WfQzKtha5ClZRXUUNUTaY+4wm8+2rqFnIa9IMKNgHnvPmLyf/J6K1ooPJHYB4HfvS/4cP0DXQTe3q9U06HeWGOiS32Jq86QRo2Zm7yUVmYu0fEU/jQIJtv3BGuzz8aeF5JGFcKOe11sETHjs7CKrK89hEtKkpmuw3V7FteWfxla8YNkhQBLqeY+z3Cq7k77DVXdupzQZwGeYBNjHECnS38PBQ35biZhZTEM0/uY9NITiQpbdga+njAK2SqHRtiw=
  - secure: CEIMGeEcS+zpdiRXAripOJxwUg5rbmO8pe4u+zm5eteoLA6idQNUEi4o2F2pyWFNZy95B3BiM3ZSMStwdJwu3tZ4cjmX3XnU5GN26tw4wYsM2bW3iNH5xi1pxjtyFTwT9h6JL+mMxOBbPK8DmOPSWEWVMkAs+bw1GLOOMHQ3q29qXUwEDrb4+SS8mAXlWmQSFT+lQVGtRbvu38F6m24qSFQVL2mB/VKty3meByvkddaKShTrhsk867eR1pAvBBjtQHiyVCGaKHHspeOsWjfnnIr2I5CEWFlHSCOQgtY7obS5G0LmNcoApc/aAEYUWcSZ1TIoY0KtK+LyTkKNzB1oaqbVt0ZlrPJUt7fXSlBKyM/UbZ8NFCsIJ+Yi/dXUrD99cPONJK4sVBO9YLmZEpVWfGd1NJs6isULZJoqqbNb9XQ59uZpR9jo9ZyR7IUsHcshQAN8mH0EJLbRtiAN9m3bA89DkdEMWph9UmwBtKYC52JHne6ENClMAk7K/IgzB20iYd4B8M5a6k43DpDUaNf6gjkhL6RrR0ssiNJsI3QmdcYodf2mDlJuYnVmaHpb8dcUBC8ImcVjYKuDst32RXvkAYKvpCy67A2FDuZ1F2CE+hbA7fIaYsN5UkkcF6nYcNJMZ6PF76WQ+2j2UgLVGOvAl91lpoo1P07fzM4P5j9bnc0=
before_install:
  - docker pull kuzzleio/documentation-v2:js
  - docker pull kuzzleio/documentation-v2:go
  - sysctl -w vm.max_map_count=262144
addons:
  apt:
    packages:
    - python
    - python-pip
install:
  - pip install awscli --upgrade --user
script:
  - sh .travis/start_kuzzle.sh
  - docker run -a stdout -a stderr --rm --privileged --network codepipeline_default --link kuzzle --mount type=bind,source="$(pwd)",target=/app kuzzleio/documentation-v2:js
  - docker rm $(docker container list -q -a) --force
  - aws s3 cp reports/ s3://$AWS_S3_BUCKET/reports/js/$TRAVIS_COMMIT/ --recursive --exclude "*.gitkeep"
  - sh .travis/start_kuzzle.sh
  - docker run -a stdout -a stderr --rm --privileged --network codepipeline_default --link kuzzle --mount type=bind,source="$(pwd)",target=/app --mount type=bind,source="$(pwd)"/test/bin,target=/go/src/github.com/kuzzleio/go-test kuzzleio/documentation-v2:go
  - docker rm $(docker container list -q -a) --force
  - aws s3 cp reports/ s3://$AWS_S3_BUCKET/reports/go/$TRAVIS_COMMIT/ --recursive --exclude "*.gitkeep"
after_script:
  - sh .travis/comment_pr.sh