---
# -----------------
# YAML Templates
# -----------------
# Production environment variables
_doc-production-env: &doc-production-env
  - BRANCH=stable
  - S3_BUCKET=docs.kuzzle.io
  - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM

# Development environment variables
_doc-development-env: &doc-development-env
  - BRANCH=dev
  - S3_BUCKET=docs-next.kuzzle.io
  - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U

# Documentaton framework build tasks
_doc-framework-build-tasks: &doc-framework-build-tasks
  before_script:
    - pip install awscli --upgrade --user
    - npm ci
  script:
    - npm run doc-build
  after_success:
    - npm run doc-upload
    - npm run doc-cloudfront

# Documentaton content build tasks
_doc-content-build-tasks: &doc-content-build-tasks
  install:
    - pip install awscli --upgrade --user
    - npm ci
  before_script:
    - npm run repositories -- clone
    - npm run repositories -- run "npm run doc-prepare" --async
  script:
    - npm run repositories -- run "npm run doc-build" --async
  after_success:
    - npm run repositories -- run "npm run doc-upload" --async
    - npm run doc-cloudfront

# Documentation deployment
_doc-deploy: &doc-deploy
  stage: Deployments
  language: node_js
  node_js: 10
  env: &doc-deploy-env
    - NODE_ENV=production
    - AWS_DEFAULT_REGION=us-west-2
    - AWS_ACCESS_KEY_ID=AKIAIYAXFUAHXOWP2MJA
    # AWS_SECRET_ACCESS_KEY
    - secure: K1Hf0b0hgRRkIbudmJZCz96ZeObzRJsC4hUZ7N1aolAKkqRcb1HeKkWwD6Ql/kp2shnQ+QQhPVDlvJSDORJ1D+vZlDiYn8fYSjgcXLC1yfkzXkbezLQGZdyTGjpRyyv2vRt1JHtvLIXLrAg4INWyR2mQR/vW8lMdJkVcXnGu+CIdvncnQfYD6axVqWmqCgElEtCOZ3RUxxm2CHSqy7Caf9hF217lxAHORW6QEtfu86WvRoiIX08W9BQpNKvbdafiu0myVTnZUkn+w0ZhTGaS+nTd7AmIbPw8wQsRbm7ex9BTR4PpZMQOE/Aqtm5T7kEbpMK+oXRKIv2Y40YKTDaC27NQl12fZ0ORR6Gttm9DqXXACW8G5F87FkYJUSC8vo8UJFJSJhAKtzsqJRY5rIAr/tSFGwtxhhE4XV2eFC25zaNJsRXhzTyDB+OF9O0EUS2YgEZVfr3cxmUIDimKOsKP918zbjvBtLrZ1KJEs/1yR05J423CZ64T0RzLJ7HATzLt7Wo/nlzij73UglntxZlXWkhmZUGkT/UeNvTE+aPbfam+BWI2Y5v3qrxvtZ9IyOhSIVAsxi+/siRjv256pJnFLgpoGX8hH6rRP0TC3ri+8Sv/xV9ZxiUgUHhOhkUB57Uv1zHEOLR23vMRU1o8y4oA16bckc2SJ3SWrFXKT4qujgI=
    # ALGOLIA_WRITE_KEY
    - secure: mwbfknkwzXmtGObr9pclB9z930GSuLydJiac1/o/m53oNkL1YqUOFmCsfZ8XFmQCIpqWVWMnKmoXgTXvSOx551IBYakGDkil/O988pmX7/Z2r4n6ONvWbj1oCciCsH6zsZ4u28R0cZ6ELiZXdiSjz+bjRtbS70lOxVHZAp9HFPBXymIa6ala683l1uMejDfDFtCc0zi7Qi69TLxj+x7ggroUhWbzg5P2J0RfnpYy+KifMcbz1hmhqNTJpvGRmYBHf6GFgcOCc78z14Aay8IVQjdVMBA3AgnqhquS97PQis+gsHRpKn5rCSj4jncTz+Xa3xfz52tZ5ElsyZSi9Qio4k3GOK/SCocjS+gbr3qdVc1BOPBkhYmwkgYVFnzKx+T+87zqnZ809SdhQa1K3pXblMenjYVPGLxt242yPwNlQfdLAbmTaahmzWTfEgSzCoqjy6EcdwFHwUC/pqCBBfSlNKKfqLIfwgR/4b5j4o2F+GjKk64qnii3uVkGShuT15tB6vAvqbLrUr2/dWQC4ORXgyZqYxuGvQVmgJ8zVqQFcC16U+eVQQYqshfInwLVcU9RFrLj37ekiEgFkklV2dggVr3gVTEEPZPlkpMHn1kP/69VkMcEyP48DBHJ8Qi26EFaH7bviuXehnK9f9HzhqC3t/q8NLr/w07izHu9yzlS9V8=
  addons:
    apt:
      packages:
        - python
        - python-pip
  cache:
    npm: true
    directories:
      - $HOME/.cache/pip

# ------------------------
# Jobs configuration
# ------------------------
jobs:
  include:
    - <<: *doc-deploy
      <<: *doc-framework-build-tasks
      name: Deploy framework to docs.kuzzle.io
      if: type = push AND branch = master
      env:
        - *doc-deploy-env
        - *doc-production-env

    - <<: *doc-deploy
      <<: *doc-framework-build-tasks
      name: Deploy framework to next-docs.kuzzle.io
      if: type = push AND branch = develop
      env:
        - *doc-deploy-env
        - *doc-development-env

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy kuzzle-1, sdk-javascript-5, sdk-javascript-6 to docs.kuzzle.io
      if: type = push AND branch = master
      env:
        - *doc-deploy-env
        - *doc-production-env
        - REPOSITORIES=kuzzle-1,sdk-javascript-5,sdk-javascript-6

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy kuzzle-1, sdk-javascript-5, sdk-javascript-6 to next-docs.kuzzle.io
      if: type = push AND branch = develop
      env:
        - *doc-deploy-env
        - *doc-development-env
        - REPOSITORIES=kuzzle-1,sdk-javascript-5,sdk-javascript-6

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy sdk-csharp-1, sdk-cpp-1, sdk-java-1, sdk-java-2, sdk-android-3 to next-docs.kuzzle.io
      if: type = push AND branch = develop
      env:
        - *doc-deploy-env
        - *doc-development-env
        - REPOSITORIES=sdk-csharp-1,sdk-cpp-1,sdk-java-1,sdk-java-2,sdk-android-3

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy sdk-csharp-1, sdk-cpp-1, sdk-java-1, sdk-java-2, sdk-android-3 to docs.kuzzle.io
      if: type = push AND branch = master
      env:
        - *doc-deploy-env
        - *doc-production-env
        - REPOSITORIES=sdk-csharp-1,sdk-cpp-1,sdk-java-1,sdk-java-2,sdk-android-3

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy plugin-cloudinary-1, plugin-s3-1, sdk-go-1, sdk-go-2, sdk-php-3 to next-docs.kuzzle.io
      if: type = push AND branch = develop
      env:
        - *doc-deploy-env
        - *doc-development-env
        - REPOSITORIES=plugin-cloudinary-1,plugin-s3-1,sdk-go-1,sdk-go-2,sdk-php-3

    - <<: *doc-deploy
      <<: *doc-content-build-tasks
      name: Deploy plugin-cloudinary-1, plugin-s3-1, sdk-go-1, sdk-go-2, sdk-php-3 to docs.kuzzle.io
      if: type = push AND branch = master
      env:
        - *doc-deploy-env
        - *doc-production-env
        - REPOSITORIES=plugin-cloudinary-1,plugin-s3-1,sdk-go-1,sdk-go-2,sdk-php-3
