sudo: required
services:
  - docker
env:
  global:
  - AWS_S3_BUCKET=docs-v2.kuzzle.io
  - secure: OzuieJA4fywQ2/cuKNvBlNbJUNaG/SJ+l+3MeJQ2GVuhXAK/MCOD7AbckNzXZc/ebM/+AfECreQrBcCJ516Vr1Q+VRwmIKk8Z7WKkuplj3/B0aRzX0Il7DRwuHCYvbqX01ghmI8FqJGHTAIDWl9WLgMRtXu6SJvyHU8yYMbQXrlMXNcBg7c52WKGfNb+tZieLJbf/wCb9WYhhbfqMpmR3DSqp1NZxlaXBVSMYef8l3/dzIv79eleH1aqS1+Vf9+hz17+QGx6/eQhxvO5BAbQ//HkmUHHk1Ii7dtjWPNRypkUqQjxpK3m8gp8wcV+jio/rF8ejWIygaxS26/RbSM8JsuWccnw8+63sCln8jr0zBGhQlJtOjIq4vrZLtlmxkyw22eCNfNETX6zU5uOO2eKdyx6NE+n+vdlLaSbxOzL5C9tCJWDryUGgalS1lynx3yq9Uh50jFZnlCz43cvzoq4q6cGqDlJv4iRoyd8cELgrI6zGWD3Yyi610dleF15B4vqmJYE/DSIQeeg8kTaUlTRwBXIzM6AhhEz5FiAXS45xV378E6W044qmfHgodZlo7bDfXHxzr7WvtIun9W6NqAu35qx4ueQPfUYs+5VcRu5Cwy9yVUPDQQMmcGwRTRtVbJq6Z8wx/wEL5kTEAK4HxRIf+lKve5PQx7p4IbFkhcP7IQ=
  - secure: Pq6UAUQbyHBzLyb148AI0h5srZxufdV0PYaVMH46q1+cyxXbF9Dlg+SToiEfZWwPHw2vvMzwmJs9qiH2itOSUs/OnobWT+zbpLWwUn77oWt+beYqgRFZMqT7FCd9wg3zIf1GRHJrXtEnNX+YtVNeeOuKPKd+akbJXRHmrwx5Ou/pDYWQn7mQZDmZXqzOcSEbi9jebLD8PBTGD2f+XB6P9CNC4dShB72i4BXN2liHo6CALPcBS8PLh2roexs8S9w2OtBaBByVYSFh/rCSiwBh4+qvKMAYuWVwMeg1sDoIex9nPm3tkfGLzBiw/PyqHjvexVMKlDLSpySiSMbY/1deEmZEzT6eYlZl2EJGCdUgZJgAb5eaQuSEgK/Mg08laYOy0XLboaxo1ysV0Td0vO9gvhj86JglMvHxb7z9zRsVbAzUcVaOAh/mguCO2ICjQB2HFsi05Ds+kb+LyAjquTX7dUnn0wJqx7T4e7Tv8CwWEbqgr3uif2YBBwUteneCWrXNUmDY87O6de44JPJNChOIgRjX18XkvKISkjc95R7uKeCvwaNvLyK50HYjoHx/rtFz7cwAtS/W/kMi5fBYewcHDG/o1SYOu7WUxsDiAzUWivSoVoJbqDDrTKGZLrq9jiwF/UNlvJBHo0Hj7ZQjYkfrgtlrAPmSehUFP7RhSkJlyC4=
before_install:
  - docker pull kuzzleio/documentation-v2:js
  - docker pull kuzzleio/documentation-v2:go
  - sysctl -w vm.max_map_count=262144
addons:
  apt:
    packages:
    - python
    - python-pip
install:
  - pip install awscli --upgrade --user
script:
  - sh .travis/start_kuzzle.sh
  - docker run -a stdout -a stderr --rm --privileged --network codepipeline_default --link kuzzle --mount type=bind,source="$(pwd)",target=/app kuzzleio/documentation-v2:js
  - docker rm $(docker container list -q -a) --force
  - aws s3 cp reports/ s3://$AWS_S3_BUCKET/reports/js/$TRAVIS_COMMIT/ --recursive --exclude "*.gitkeep"
  - sh .travis/start_kuzzle.sh
  - docker run -a stdout -a stderr --rm --privileged --network codepipeline_default --link kuzzle --mount type=bind,source="$(pwd)",target=/app --mount type=bind,source="$(pwd)"/test/bin,target=/go/src/github.com/kuzzleio/go-testkuzzleio/documentation-v2:go
  - docker rm $(docker container list -q -a) --force
  - aws s3 cp reports/ s3://$AWS_S3_BUCKET/reports/go/$TRAVIS_COMMIT/ --recursive --exclude "*.gitkeep"
